FROM python:3.13-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Para que Python encuentre los módulos (db, models, functions, etc.)
ENV PYTHONPATH=/app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el proyecto
COPY . /app

# Exponer el puerto de FastAPI
EXPOSE 8000

# Levantar la app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
